const sampleData = [
  {
    heading: "Crop Insurance",
    shortDescription: "Protect crops from loss.",
    image:
      "https://1.bp.blogspot.com/-A_SwOCcDKfg/X0TIHtnGFkI/AAAAAAAAAb8/1_79PlKPqqgHKa1JVIuoOZzLXxMlcBh-ACLcBGAsYHQ/s2048/Crop-Insurance-Online.jpg7",
    description:
      "The Crop Insurance Scheme provides financial support to farmers in case of crop failure due to natural calamities, pests, and diseases. It helps farmers stabilize their income and encourages them to adopt innovative farming practices. The scheme covers all food crops, oilseeds, and commercial/horticultural crops, ensuring comprehensive protection against a wide range of risks.By offering financial security, the scheme enables farmers to invest in quality inputs and modern farming techniques, thereby enhancing their productivity and income levels. This scheme also promotes the overall resilience of the agricultural sector, contributing to food security and sustainable development. Additionally, it reduces the dependency on informal credit sources and mitigates the distress caused by crop loss, ultimately fostering a more sustainable agricultural economy.The scheme also facilitates access to institutional credit, as lenders are more willing to provide loans to farmers who have insurance coverage. This access to credit is crucial for farmers to purchase high-quality seeds, fertilizers, and equipment, further improving their productivity and profitability. Moreover, the scheme plays a vital role in maintaining the stability of rural economies by preventing sudden financial shocks due to crop failures. By protecting the income of farmers, it helps in sustaining the overall economic activities in rural areas, thereby contributing to rural development.Furthermore, the scheme includes an awareness and education component, ensuring that farmers are well-informed about the benefits and procedures of crop insurance. Training programs and workshops are conducted to educate farmers on risk management and the importance of insurance in mitigating agricultural risks. This holistic approach not only provides financial support but also empowers farmers with the knowledge and tools to enhance their agricultural practices, leading to long-term sustainability and resilience in the agricultural sector.",
    schemeType: "schemes",
  },
  {
    heading: "Soil Health Card",
    shortDescription: "Monitor soil quality.",
    image:
      "https://up.yimg.com/ib/th?id=OIP.cvBDSgBUpXVz5zioiHUe2AHaEK&pid=Api&rs=1&c=1&qlt=95&w=209&h=117",
    description:
      "The Soil Health Card Scheme aims to assist farmers in understanding the health of their soil and improve its productivity. The card provides information on nutrient status and recommendations on appropriate dosage of fertilizers. By regularly monitoring soil quality, farmers can make informed decisions about soil management, leading to better crop yields and sustainable farming practices.The scheme not only helps in maintaining soil fertility but also in preventing the overuse of fertilizers, which can harm the environment. It empowers farmers with knowledge, enabling them to implement effective soil conservation techniques and enhance the long-term health of their farmlands. Furthermore, the scheme supports the government's broader goals of promoting sustainable agriculture and improving the livelihood of farmers by ensuring they use their land resources efficiently.Regular monitoring and assessment of soil health also help in identifying and addressing soil degradation issues promptly. Farmers receive tailored advice on soil amendments and practices to restore soil health, ensuring sustainable land use. The scheme promotes the adoption of organic farming practices and the use of bio-fertilizers, contributing to environmentally friendly agricultural practices. By maintaining soil health, the scheme ensures that the land remains productive for future generations, supporting long-term agricultural sustainability.Additionally, the Soil Health Card Scheme fosters a collaborative approach involving agricultural scientists, extension workers, and farmers. This collaboration enhances the dissemination of knowledge and best practices related to soil management. Farmers are encouraged to participate in soil testing campaigns and workshops, where they learn about the importance of soil health and receive hands-on training in soil sampling and interpretation of test results. This interactive approach not only empowers farmers with valuable knowledge but also creates a sense of ownership and responsibility towards maintaining soil health.",
    schemeType: "schemes",
  },
  {
    heading: "PM-KISAN",
    shortDescription: "Direct income support.",
    image:
      "https://media.lendingkart.com/wp-content/uploads/2022/06/PM-Kisan.jpg",
    description:
      "The Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) provides direct income support to farmers. Eligible farmers receive financial assistance to help them meet agricultural and household needs, ensuring a stable income. The scheme aims to augment the income of small and marginal farmers by providing them with an assured source of income, which can be used for purchasing inputs, meeting domestic needs, or investing in farm improvements.By reducing the financial burden on farmers, PM-KISAN helps in boosting their morale and enables them to focus on improving productivity. This scheme is a significant step towards achieving the government's vision of doubling farmers' income and promoting rural prosperity. It also plays a crucial role in enhancing the socio-economic status of farmers by providing them with a steady financial foundation and fostering a more resilient agricultural sector.The scheme also includes provisions for grievance redressal, ensuring that farmers can report and resolve issues related to fund disbursement efficiently. This responsiveness enhances the credibility and trustworthiness of the scheme among the farming community. Furthermore, PM-KISAN supports the goal of financial inclusion by encouraging farmers to open bank accounts, thereby integrating them into the formal financial system. This access to banking services also opens up opportunities for farmers to avail themselves of other financial products and services, such as credit, savings, and insurance.Additionally, PM-KISAN promotes the use of digital technologies in agriculture by encouraging farmers to use mobile applications and online platforms for accessing scheme-related information. This digital push not only facilitates easier access to government services but also empowers farmers with real-time information on weather, market prices, and best agricultural practices. The scheme's holistic approach ensures that financial support is complemented by knowledge and resources that enable farmers to enhance their agricultural productivity and overall well-being.",
    schemeType: "schemes",
  },
  {
    heading: "Fertilizer Subsidy",
    shortDescription: "Affordable fertilizers.",
    image:
      "https://tse1.mm.bing.net/th?id=OIP.uDuvaPmJsqw42WmmckKcCAHaE6&pid=Api",
    description:
      "The Fertilizer Subsidy Scheme ensures that fertilizers are available to farmers at affordable prices. This subsidy reduces the cost of farming and helps increase agricultural productivity. By making fertilizers more accessible, the scheme encourages farmers to use balanced and adequate doses of nutrients, which are essential for healthy crop growth.The availability of subsidized fertilizers also promotes equitable distribution, ensuring that even small and marginal farmers can benefit from improved crop yields. Furthermore, the scheme plays a crucial role in sustaining soil fertility, preventing nutrient depletion, and supporting the long-term sustainability of agricultural production. By reducing the financial burden on farmers, it helps them focus on improving their farming practices and overall productivity.The scheme also promotes the use of bio-fertilizers and organic manures as part of an integrated nutrient management approach. This encourages sustainable farming practices and reduces dependency on chemical fertilizers, contributing to environmental conservation. By improving nutrient management, the scheme enhances the quality and quantity of agricultural produce, leading to higher incomes for farmers. The increased agricultural productivity also supports food security by ensuring a stable supply of essential food crops.Additionally, the Fertilizer Subsidy Scheme includes provisions for monitoring and evaluation to ensure the effective implementation of the subsidy and prevent misuse. Farmers are educated about the appropriate use of fertilizers through training programs and extension services, ensuring that they apply the correct quantities at the right time. This knowledge transfer helps in optimizing the use of inputs and maximizing crop yields. The scheme's comprehensive approach not only provides financial support but also empowers farmers with the knowledge and resources to enhance their agricultural practices sustainably.",
    schemeType: "subsidies",
  },
  {
    heading: "Agricultural Mechanization",
    shortDescription: "Modern farming tools.",
    image:
      "https://tse1.mm.bing.net/th?id=OIP.0pJbHq8K9pqnlCFcQC_eHgHaEK&pid=Api&P=0&h=220",
    description:
      "The Agricultural Mechanization Scheme promotes the use of modern farming equipment and machinery. Subsidies are provided to farmers for purchasing tools that enhance efficiency and reduce labor costs. By adopting mechanization, farmers can perform agricultural operations more quickly and accurately, leading to higher productivity and better crop management.The scheme also aims to address the issue of labor shortages in rural areas, making farming more viable and attractive. Through the introduction of advanced machinery, the scheme supports sustainable agricultural practices, reduces physical drudgery, and contributes to the overall economic growth of the farming community. Additionally, it helps farmers adopt precision farming techniques, leading to optimized resource use and improved crop yields.The use of machinery also enables farmers to expand their cultivation areas and diversify their crops, increasing their income potential. By reducing reliance on manual labor, the scheme enhances the efficiency of farming operations and improves the quality of life for farmers. The adoption of mechanized practices also leads to better resource management, reducing wastage of inputs such as seeds, fertilizers, and water. This contributes to the overall sustainability and profitability of agricultural activities.Moreover, the scheme includes training programs for farmers on the operation and maintenance of agricultural machinery. This ensures that farmers can use the equipment effectively and extend its lifespan through proper care. The availability of technical support and service centers further enhances the utility of the machinery, ensuring that farmers can get timely repairs and maintenance. By integrating modern technology into agriculture, the Agricultural Mechanization Scheme empowers farmers to achieve higher productivity and sustainability.",
    schemeType: "schemes",
  },
  {
    heading: "Irrigation Development",
    shortDescription: "Efficient water use.",
    image:
      "https://www.gannett-cdn.com/-mm-/6c8b30d579d9e1d308b39d6a1715e972565ee2ec/c=0-1-775-439/local/-/media/2017/01/19/TXNMGroup/LasCruces/636204658625028220-irrigation.jpg?width=3200&height=1680&fit=crop",
    description:
      "The Irrigation Development Scheme focuses on improving irrigation facilities to ensure efficient water use. This includes building canals, ponds, and rainwater harvesting structures to support sustainable agriculture. The scheme aims to enhance the availability and accessibility of water resources for agricultural purposes, reducing the dependency on monsoon rains.By implementing advanced irrigation techniques, the scheme promotes water conservation and efficient utilization, which are crucial for sustainable farming. It also helps in mitigating the impact of droughts and water scarcity, ensuring that crops receive adequate water supply throughout their growth cycle. Ultimately, the scheme contributes to increased agricultural productivity and resilience, fostering a more stable and prosperous farming community.Furthermore, the scheme promotes the adoption of water-saving technologies and practices, encouraging farmers to use water resources judiciously. Training programs and awareness campaigns are conducted to educate farmers about the benefits of efficient water management and the importance of conserving water. This knowledge transfer helps farmers implement best practices in irrigation, reducing water wastage and enhancing agricultural sustainability. The scheme also includes provisions for monitoring and evaluating the effectiveness of irrigation projects, ensuring that the intended benefits are realized.Additionally, the scheme fosters collaboration between government agencies, research institutions, and farmers to develop innovative solutions for water management. This collaborative approach ensures that farmers have access to the latest technologies and techniques for efficient irrigation. By improving water infrastructure and management practices, the Irrigation Development Scheme contributes to the overall resilience and sustainability of the agricultural sector, supporting the livelihoods of farmers and promoting rural development.",
    schemeType: "schemes",
  },
  {
    heading: "Organic Farming",
    shortDescription: "Promote organic produce.",
    image:
      "https://tse3.mm.bing.net/th?id=OIP.Bhhnr1wG98iayB2ZQ_ibjAHaEK&pid=Api&P=0&h=220",
    description:
      "The Organic Farming Scheme encourages farmers to adopt organic farming practices. It provides financial assistance for organic certification, inputs, and market linkages to promote the production of organic food. By reducing the use of chemical fertilizers and pesticides, the scheme supports environmentally sustainable farming practices.Organic farming not only improves soil health and biodiversity but also enhances the quality of produce, making it safer for consumers. The scheme aims to create a market for organic products, ensuring better prices for farmers and promoting healthier food options. Additionally, it contributes to the overall goal of sustainable agriculture by encouraging eco-friendly farming practices and reducing the carbon footprint of agricultural activities.Moreover, the scheme includes training and capacity-building programs to educate farmers about organic farming techniques and best practices. Farmers learn about composting, crop rotation, and natural pest management, enabling them to produce high-quality organic crops. The scheme also facilitates the establishment of organic farmer groups and cooperatives, promoting collective marketing and enhancing the bargaining power of farmers. This collective approach helps in achieving economies of scale and better market access for organic produce.Furthermore, the scheme supports research and development in organic farming, promoting the adoption of innovative technologies and practices. Research institutions and agricultural universities collaborate with farmers to develop and disseminate knowledge on organic farming methods. The scheme also includes provisions for creating awareness among consumers about the benefits of organic food, thereby increasing demand and supporting the growth of the organic farming sector. By fostering a holistic approach to organic farming, the scheme ensures long-term sustainability and profitability for farmers.",
    schemeType: "schemes",
  },
  {
    heading: "Seed Subsidy",
    shortDescription: "Quality seeds for all.",
    image: "https://kj1bcdn.b-cdn.net/media/30377/subsidy.jpg",
    description:
      "The Seed Subsidy Scheme provides high-quality seeds to farmers at subsidized rates. This ensures access to improved seed varieties that are high yielding and disease-resistant, contributing to increased agricultural productivity. By using superior seeds, farmers can achieve better crop performance and resilience against pests and diseases.The scheme also promotes the adoption of new and improved seed varieties, encouraging innovation and diversification in cropping patterns. This not only enhances the productivity and profitability of farming but also supports food security by ensuring a stable supply of high-quality produce. Additionally, the scheme aims to reduce the financial burden on farmers, making quality seeds more affordable and accessible to all.Furthermore, the scheme promotes the use of certified and genetically improved seeds, ensuring that farmers can achieve higher yields and better crop quality. The use of high-quality seeds also reduces the risk of crop failure and enhances the resilience of farming systems. Training programs and awareness campaigns are conducted to educate farmers about the importance of using certified seeds and the benefits of adopting improved seed varieties. This knowledge transfer helps in increasing the adoption rate of quality seeds, leading to better agricultural outcomes.Additionally, the scheme includes provisions for establishing seed banks and storage facilities, ensuring the availability of seeds during critical planting seasons. Seed banks play a crucial role in maintaining a steady supply of quality seeds and providing farmers with timely access to inputs. The scheme also supports research and development in seed technology, promoting the development of new and improved seed varieties. By fostering innovation and ensuring the availability of quality seeds, the Seed Subsidy Scheme contributes to the overall growth and sustainability of the agricultural sector.",
    schemeType: "subsidies",
  },
  {
    heading: "Agri-Clinic",
    shortDescription: "Expert advice for farmers.",
    image:
      "https://tse3.mm.bing.net/th?id=OIP.MpcoSoCeRfiqrUKLVLC2HQHaE7&pid=Api&P=0&h=220",
    description:
      "The Agri-Clinic Scheme establishes centers where farmers can get expert advice on various agricultural issues. These clinics offer guidance on crop management, pest control, soil health, and more, helping farmers improve their productivity. By providing access to professional agricultural advice, the scheme helps farmers adopt best practices and modern techniques.The Agri-Clinics also serve as a platform for disseminating information about new technologies and government schemes, ensuring that farmers are well-informed and can make better decisions. This initiative not only improves the overall efficiency of farming operations but also empowers farmers with the knowledge and skills needed to enhance their livelihoods. By fostering a culture of continuous learning and improvement, the scheme contributes to the sustainable development of the agricultural sector.Moreover, the Agri-Clinic Scheme includes training programs for agricultural graduates, equipping them with the skills and knowledge to provide professional services to farmers. These trained professionals act as agricultural advisors, bridging the gap between research institutions and the farming community. The scheme also promotes the establishment of Agri-Clinics in remote and underserved areas, ensuring that farmers in all regions have access to expert advice and support. This inclusive approach helps in addressing regional disparities and promoting equitable growth in agriculture.Furthermore, the scheme encourages the use of digital tools and technologies in Agri-Clinics, enhancing the efficiency and reach of advisory services. Farmers can access information and advice through mobile applications, helplines, and online platforms, ensuring timely and convenient support. The integration of digital technologies also facilitates the collection and analysis of data, enabling more accurate and personalized recommendations. By leveraging technology and expertise, the Agri-Clinic Scheme empowers farmers to achieve higher productivity and sustainability.",
    schemeType: "products",
  },
  {
    heading: "Drone Technology",
    shortDescription: "Precision farming.",
    image:
      "https://tse4.mm.bing.net/th?id=OIP.dDlBrv47rtQBVCsk-SlCKwHaEK&pid=Api&P=0&h=220",
    description:
      "The Drone Technology Scheme promotes the use of drones in agriculture for precision farming. Drones are used for monitoring crop health, spraying fertilizers and pesticides, and collecting data to optimize farming practices. By utilizing advanced technology, the scheme aims to improve the accuracy and efficiency of agricultural operations.Drones provide real-time data and high-resolution imagery, enabling farmers to make informed decisions about crop management. This not only helps in detecting and addressing issues early but also reduces the wastage of inputs and resources. The scheme supports the adoption of innovative technologies, enhancing the overall productivity and sustainability of farming practices. By integrating modern technology into agriculture, it paves the way for a more efficient and data-driven approach to farming.Furthermore, the scheme includes training programs for farmers on the use of drones and the interpretation of data collected. This ensures that farmers can effectively utilize drone technology and make the most of its benefits. The scheme also promotes collaboration between technology providers, research institutions, and farmers to develop and refine drone applications in agriculture. This collaborative approach ensures that the technology is tailored to meet the specific needs of farmers and addresses the challenges they face in crop management.Additionally, the scheme supports the development of infrastructure and regulatory frameworks for the safe and effective use of drones in agriculture. This includes establishing guidelines for drone operations, ensuring data privacy, and providing technical support for farmers. By creating a conducive environment for the adoption of drone technology, the scheme facilitates the integration of advanced tools in agriculture. This not only enhances productivity and sustainability but also positions agriculture as a technologically advanced and innovative sector, attracting investment and fostering growth.",
    schemeType: "newTech",
  },
];

export default sampleData;
